os: linux
language: node_js
node_js:
  - 13
  - 12
  - 10
  - 10.3
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      before_install:
        - npm i -g codecov
      script:
        - npm run verify
        - npm run test:ci
      after_success:
        - codecov
    - stage: deploy
      node_js: 13
      install: true
      before_script:
        - chmod +x publish-website.sh
      script:
        - ./publish-website.sh
notifications:
  email:
    on_success: never
    on_failure: always
